Added song duration, max/min val printing
Need to check read samples, because simplemad is throwing errors when running:
```
Song duration: 348.055497152s
Error: Mad(LostSync)
Error: Mad(BadLayer)
Error: Mad(LostSync)
Error: Mad(BadDataPtr)
Error: Mad(LostSync)
Read 13323 samples from mp3, with range [Some(
    -268114611,
),Some(
    263054941,
)]
```